### ISSUE TITLE
Different DICOM variants upload.

### ISSUE THREAD

**Issue by Darkoon** [jpowie01/MedTagger#114]
## Expected Behavior

More liberal approach when uploading dicom files with interactive error handling. User will upload his dataset and receive error messages for scans/slices that are corrupted or incompatible with dicom standard.

## Actual Behavior

There are problems with some dicom datasets from initial upload procedures on frontend to internal problems in backend processing.

## Additional comment

Some kind of strategy is needed because dicom files really differs from one to another. We dont want to limit users but it is impossible to process all variations of dicom formats.

**Comment by jpowie01** [comment]
I think it is high time to Close this Issue as it seems to be resolved.
The only thing that will improve upload of different DICOMs is this Issue #211.
