### ISSUE TITLE
Page is overlayed by bottom footer if page is longer than one screen

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#117]
## Expected Behavior

There should be a bigger bottom margin.

## Actual Behavior

Footer overlay the page if it's longer than one screen.

## Steps to Reproduce the Problem

  1. Add multiple users (~50). 
  2. Go to the Admin Panel to see list of all users.
  3. Scroll down.

![screen shot 2018-03-14 at 13 30 25](https://user-images.githubusercontent.com/6514553/37402755-07acde10-278d-11e8-81d4-129b842be26f.png)

**Comment by kolszewska** [comment]
Possible that this no longer will be an issue after we introduce new design.

**Comment by jpowie01** [comment]
No longer an issue. UI was redesigned 🚀
