### ISSUE TITLE
Desing and implement changing scans Hounsfield window from admin page

### ISSUE THREAD

**Issue by kolszewska** [jpowie01/MedTagger#134]
## Expected Behavior

After scans are uploaded the owner of the scan or admin should be able to view converted images. If the image is unfit to be used for labeling (e.g too dark) the owner should be able to preview the image with a new Hounsfield window and then start new conversion to PNG files.  

## Actual Behavior

There is no possibility to change scans Hounsfield window after scans are uploaded.

## Additional comment

It needs to be decided if this conversion on demand should be enabled only for not yet labeled scans. As the already made labels may have been impacted by poor image conditions. 

Possibly connected to #128 so the admin would get notification from users telling that scan require on-demand conversion using new Hounsfield window.

**Comment by jpowie01** [comment]
Design is done. Implementation has been splitted into multiple Issues: #211, #178, #212.
