### ISSUE TITLE
Provide support for LabelTags in repositories

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#164]
## Expected Behavior

Repositories should:
- be ready to add LabelTags to given ScanCategory,
- query for Labels by LabelTag,
- add new Labels with LabelTag,
- allow to edit LabelTags,
- allow to delete LabelTags,
- ...many more you will find useful.

**Comment by kolszewska** [comment]
Propositions for ScanCategory repository:
- get all LabelTags for ScanCategory,
- add LabelTags to ScanCategory,
- delete LabelTags from ScanCategory.

Label Repository:

- add new label with LabelTag,
- get labels with LabelTag,

LabelTags:
- edit LabelTags,
- deleteLabelTags.
