### ISSUE TITLE
Add support for LabelTags in scripts that set up whole environment

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#166]
## Expected Behavior

MedTagger should add LabelTags with tools to default ScanCategories that are being added during environment setup (both for development and Docker-Compose).

Keep in mind that it should also work while your setup may already exists and you want to upgrade your dev instance to the latest version of code.

**Comment by kolszewska** [comment]
- [ ] backup_medtagger.py
- [ ] fixutres.py
