### ISSUE TITLE
Update videos on tutorial page with new design

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#21]
## Expected Behavior

Videos on tutorial page should be using English labels/texts.

## Actual Behavior

MedTagger's frontend's first implementation was purely in Polish. It resulted in many labels/buttons/error messages that are still using Polish language. Videos on tutorial page were recorded on the old version of MedTagger which was using Polish.

## Steps to Reproduce the Problem

  1. Go to tutorial page.

**Comment by Darkoon** [comment]
#58
