### ISSUE TITLE
Refactor Scan Categories to something more generic

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#314]
## Expected Behavior

There should be a generic entity for **"an examination"** or **"a task"**.

## Actual Behavior

Right now, there is a "Scan Category" that plays role of a container for Scans and defines available Tools with Tags. But after so long, "Scan Category" name is outdated and it is now something more generic. We should change the name for it ASAP! :)

**Let's discuss it first!**

**Comment by piotrwalkusz1** [comment]
We should allow users to create many Tasks (where Task is, for example, selecting cars) that refer to a single DataSet (where DataSet is a collection of images, scans, ...). During uploading of an image, a user chooses DataSet. Also, one Task should be able to refer to many DataSets.
